export const styles = {
  button: {
    width: 300,
    border: "none",
    backgroundColor: "#445",
    padding: 10,
    borderRadius: 5,
    margin: 5,
    color: "#ddd",
    fontSize: 15,
    letterSpacing: 2,
  },
  input: {
    width: 300,
    border: "none",
    backgroundColor: "#445",
    padding: 10,
    borderRadius: 5,
    margin: 5,
    color: "#ddd",
    fontSize: 15,
    letterSpacing: 2,
  },
  screen: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
  },
  video: {
    backgroundColor: "#888",
    transform: "scaleX(-1)",
  },
};
